// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjF45wSweueiB5AoO9bbb3ubQXJQBU6AU',
    appId: '1:237979612852:web:381948d643dda307a609e1',
    messagingSenderId: '237979612852',
    projectId: 'pawtai-mockup',
    authDomain: 'pawtai-mockup.firebaseapp.com',
    storageBucket: 'pawtai-mockup.appspot.com',
    measurementId: 'G-12HCJXN4JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwgU3qR0lutwRLJR_XCNBHItnuGK0G2Y',
    appId: '1:237979612852:android:30a3564d9d1672c6a609e1',
    messagingSenderId: '237979612852',
    projectId: 'pawtai-mockup',
    storageBucket: 'pawtai-mockup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw6LtQcN-86fRdwHKC7p34FYrpfXHp4mc',
    appId: '1:237979612852:ios:d6ab53cd61d2d52ba609e1',
    messagingSenderId: '237979612852',
    projectId: 'pawtai-mockup',
    storageBucket: 'pawtai-mockup.appspot.com',
    iosClientId:
        '237979612852-ufpij0tdu9eun3eu1aige0sqp6d0fb72.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawtaiMockup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw6LtQcN-86fRdwHKC7p34FYrpfXHp4mc',
    appId: '1:237979612852:ios:8062ecaf1af29595a609e1',
    messagingSenderId: '237979612852',
    projectId: 'pawtai-mockup',
    storageBucket: 'pawtai-mockup.appspot.com',
    iosClientId:
        '237979612852-jurmsrvk4bengrnv0tnsu91e7tm2f891.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawtaiMockup.RunnerTests',
  );
}
